# Generated by Django 3.2.3 on 2021-05-29 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_ticker',
            fields=[
                ('company_name', models.CharField(max_length=300)),
                ('stock_symbol', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('ipo_year', models.SmallIntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=300, null=True)),
                ('industry', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='intraday_stock_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockanalytics.stock_ticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='eod_stock_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockanalytics.stock_ticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
