# Generated by Django 3.2.3 on 2021-05-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eod_stock_price',
            name='ticker',
            field=models.CharField(max_length=50),
        ),
    ]
